
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// ADMIN
export const CREATE_ADMIN_SUCCESS = "CREATE_ADMIN_SUCCESS";
export const DELETE_ADMIN_SUCCESS = "DELETE_ADMIN_SUCCESS";
export const FINDBYIDOREMAILANDPASSWORD_ADMIN_SUCCESS = "FINDBYIDOREMAILANDPASSWORD_ADMIN_SUCCESS";
export const FINDBYEMAIL_ADMIN_SUCCESS = "FINDBYEMAIL_ADMIN_SUCCESS";
export const GET_ADMIN_SUCCESS = "GET_ADMIN_SUCCESS";

// ANNOUNCEMENT

// ATTENDANCE

// BLACKBOAD

// CLASS

// CLASSRESOURCES

// EXAMRESULTS

// HOMEWORKRESULTS

// LECTURER
export const CREATE_LECTURER_SUCCESS = "CREATE_LECTURER_SUCCESS";
export const DELETE_LECTURER_SUCCESS = "DELETE_LECTURER_SUCCESS";
export const GET_LECTURER_SUCCESS = "GET_LECTURER_SUCCESS";
export const LIST_LECTURER_SUCCESS = "LIST_LECTURER_SUCCESS";
export const UPDATE_LECTURER_SUCCESS = "UPDATE_LECTURER_SUCCESS";

// LESSON

// STUDENT
export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const FINDBYNAME_STUDENT_SUCCESS = "FINDBYNAME_STUDENT_SUCCESS";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export const LIST_STUDENT_SUCCESS = "LIST_STUDENT_SUCCESS";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";

// TIMETABLE

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
